_target_: dashboard.components.build_section
name: "Haas CNC"
fields:
  -
    _target_: dashboard.components.build_table
    name: "Machine Coordinates"                       # Machine coord fields comprised of five separate axis locations
    fields:                                           # x, y, z coords measured in inches on the Haas
      -
        name: x
        data: 0
        postfix: "in"
      -
        name: y
        data: 0
        postfix: "in"
      -
        name: z
        data: 0
        postfix: "in"
      -                                               # a, b (rotational axes) measured in degrees on the Haas
        name: a
        data: 0
        postfix: "deg"
      -
        name: b
        data: 0
        postfix: "deg"

  - 
    _target_: dashboard.components.build_table
    name: "Work Coordinates"                          # Work coord fields comprised of five separate axis locations
    fields:                                           # x, y, z coords measured in inches on the Haas
      -
        name: x
        data: 0
        postfix: "in"
      -
        name: y
        data: 0
        postfix: "in"
      -
        name: z
        data: 0
        postfix: "in"
      -                                               # a, b (rotational axes) measured in degrees on the Haas
        name: a
        data: 0
        postfix: "deg"
      -
        name: b
        data: 0
        postfix: "deg"
  -
    _target_: dashboard.components.build_table
    name: "Rates"                                     # Key measured rate on the Haas is spindle speed
    fields:
      -
        name: "Spindle Speed"
        data: 0
        postfix: "RPM"                                # measured in rotations per minute

  -
    _target_: dashboard.components.build_table
    name: "Status"                                    # Key status field is the coolant level of the machine
    fields:
      -
        name: "Coolant Level"
        data: 0
        postfix: ""
