_target_: dashboard.components.build_section
name: "Turtle Bot"
fields:
  -
    _target_: dashboard.components.build_table
    name: "Position"
    fields:
      -
        name: x
        data: 0
        postfix: "m"
      -
        name: y
        data: 0
        postfix: "m"

  -
    _target_: dashboard.components.build_table
    name: "Rates and Status"
    fields:
      -
        name: "Speed"
        data: 0
        postfix: "mph"      # postpend units

      -
        name: "Battery Remaining"
        data: 100
        postfix: "%"        # postpend units

      -
        name: "Temperature"
        data: 0
        postfix: "\u00b0F"   # postpend degrees symbol
